
- name: The Play
  hosts: localhost
  vars_files:
    - vars/users.yml
    - vars/packages.yml
    - vars/runtime_credentials.vault.yml
    - vars/graduated_credentials.vault.yml
  vars:
    install_dir: /opt/calvinball-website
    cockpit_module_install_dir: /opt/cockpit_modules/cvb-rebuild-site

  task:

    - name: Template backup credentials
      ansible.builtin.template:
        src: "{{ install_dir }}/backup_to_nas.sh.example"
        dest: "{{ install_dir }}/backup_to_nas.sh"
        mode: 'u+rwx'

## create cron jobs

    - name: Set MAILTO to nothing
      ansible.builtin.cron:
        env: true
        name: MAILTO
        job: ""
        state: present

    - name: Create cron job for periodic remote checks
      ansible.builtin.cron:
        name: "periodic remote checks"
        user: developer
        job: "cd \"{{ install_dir }}\" && echo \"start\" > start.log && bundle exec ruby scripts/podcast_resources.rb 2>&1 > podcast_resources.log "
        minute: "13,28,43,58"

    - name: Cron job to backup to NAS
      ansible.builtin.cron:
        name: "backup to NAS"
        user: developer
        job: "{{ install_dir }}/backup_to_nas.sh"
        minute: "0"
        hour: "1"